# Generated by Django 5.1.3 on 2024-11-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_inmueble_arrendador'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='arrendada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
