# Generated by Django 5.1.3 on 2024-11-20 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0006_clasificacion_inmueble_alter_inmueble_tipo_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.region'),
            preserve_default=False,
        ),
    ]
