# Generated by Django 5.1.3 on 2024-11-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0008_inmueble_fecha_creacion_inmueble_ultima_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='arrendada',
            field=models.BooleanField(default=False),
        ),
    ]
