# Generated by Django 5.1.3 on 2024-11-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0009_alter_inmueble_arrendada'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen_portada',
            field=models.URLField(blank=True, default=0, null=True),
        ),
    ]
