# Generated by Django 5.1.3 on 2024-11-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0014_alter_inmueble_imagen_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen1',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen2',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen3',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen4',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen5',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
