# Generated by Django 5.1.3 on 2024-11-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='enlace_whatsapp',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
