# Generated by Django 5.1.3 on 2024-11-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_enlace_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='enlace_whatsapp',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
